# ms-events
http://ms-events$SERVICES_SUFFIX:
  - path: /ping/events
    at: /ping
    method: get
  - path: /events/:eventId
    at: /:eventId
    method: get
  - path: /events
    at: /
    method: get
  - path: /events
    at: /
    method: post
    authenticated: true
  - path: /events/:eventId
    at: /:eventId
    method: put
    authenticated: true
  - path: /events/:eventId
    at: /:eventId
    method: delete
    authenticated: true
  - path: /events/:groupId/past
    at: /:groupId/past
    method: get
  - path: /events/:eventId/rsvps
    at: /:eventId/rsvps
    method: patch
    authenticated: true
  - path: /events/:eventId/agenda
    at: /:eventId/agenda
    method: put
    authenticated: true
  - path: /events/:groupId/upcoming
    at: /:groupId/upcoming
    method: get
  - path: /events/:eventId/attendees
    at: /:eventId/attendees
    method: get
  - path: /events/:eventId/rsvps/declined
    at: /:eventId/rsvps/declined
    method: patch
    authenticated: true
  - path: /events/:eventId/rsvps/confirmed
    at: /:eventId/rsvps/confirmed
    method: patch
    authenticated: true
  - path: /events/:eventId/rsvps/waiting
    at: /:eventId/rsvps/waiting
    method: patch
    authenticated: true
  - path: /groups/:groupId/events
    at: /?:groupId
    method: get

# ms-profiles
http://ms-profiles$SERVICES_SUFFIX:
  - path: /ping/profiles
    at: /ping
    method: get
  - path: /profiles
    at: /
    method: get
    authenticated: true
  - path: /profiles
    at: /
    method: post
  - path: /profiles/availability
    at: /availability
    method: get
  - path: /profiles/:id
    at: /:id
    method: get
  - path: /profiles/:id
    at: /:id
    method: put
    authenticated: true
  - path: /profiles/:userId/groups
    at: /:userId/groups
    method: post
    authenticated: true
  - path: /profiles/:id/groups/:group
    at: /:id/groups/:group
    method: delete
    authenticated: true
  - path: /groups/:group/followers?count
    at: /?:group?count
    method: get
  - path: /groups/:group/followers
    at: /?:group
    method: get
  - path: /me/groups
    method: get
    authenticated: true

# ms-user
http://ms-users$SERVICES_SUFFIX:
  - path: /ping/users
    at: /ping
    method: get
  - path: "/users/me"
    at: "/me"
    method: put
    authenticated: true
  - path: "/users/me"
    at: "/me"
    method: get
    authenticated: true
  - path: "/users/me"
    at: "/me"
    method: delete
    authenticated: true
  - path: "/users/me/password"
    at: "/me/password"
    method: put
    authenticated: true
  - path: "/users/"
    at: "/"
    method: post
  - path: "/users/:userId"
    at: "/:userId"
    method: delete
    authenticated: true
    types:
      - admin
  - path: "/users/:userId"
    at: "/:userId"
    method: get
    authenticated: true
    types:
      - admin
  - path: "/users/"
    at: "/"
    method: get
    authenticated: true
    types:
      - admin
  - path: "/users/password-recovery"
    at: "/password-recovery"
    method: post
  - path: "/users/password-recovery"
    at: "/password-recovery"
    method: put
  - path: "/users/login"
    at: "/login"
    method: post
  - path: /users/:username/availability
    at: /:username/availability
    method: get

# ms-groups
http://ms-groups$SERVICES_SUFFIX:
  - path: /ping/groups
    at: /ping
    method: get
  - path: /groups/:group
    at: /:group
    method: get
  - path: /groups
    at: /
    method: get
  - path: /groups/:groupId/followers
    at: /:groupId/followers
    method: get
  - path: /groups
    at: /
    method: post
    authenticated: true
  - path: /groups/:groupId
    at: /:groupId
    method: put
    authenticated: true
  - path: /groups/:groupId
    at: /:groupId
    method: delete
    authenticated: true
  - path: /users/:userId/groups
    at: /:userId/groups
    method: get
  - path: /groups?organizer=:organizer
    at: /organizers/:organizer/groups
    method: get

# ms-templates
http://ms-templates$SERVICES_SUFFIX:
  - path: /ping/templates
    at: /ping
    method: get
  - path: /templates/:templateId
    at: /templates/:templateId
    method: get
    authenticated: true
  - path: /templates
    at: /templates
    method: get
    authenticated: true
  - path: /templates
    at: /templates
    method: post
    authenticated: true
  - path: /templates/:templateId
    at: /templates/:templateId
    method: put
    authenticated: true
  - path: /templates/:templateId
    at: /templates/:templateId
    method: delete
    authenticated: true

# ms-certificates
http://ms-certificates$SERVICES_SUFFIX:
  - path: /ping/certificates
    at: /ping
    method: get
  - path: /certificates
    method: post
    authenticated: true
