# ms-events
http://ms-events$SERVICES_SUFFIX:
  - path: /ping/events
    at: /ping
    method: get
  - path: /events/:eventId
    at: /:eventId
    method: get
  - path: /events/
    at: /
    method: get
  - path: /events/
    at: /
    method: post
    authenticated: true
  - path: /events/:eventId
    at: /:eventId
    method: put
    authenticated: true
  - path: /events/:eventId
    at: /:eventId
    method: delete
    authenticated: true

# ms-user
http://ms-users$SERVICES_SUFFIX:
  - path: /ping/users
    at: /ping
    method: get
  - path: /users/:userId
    at: /:userId
    method: get
  - path: /users/
    at: /
    method: get
    authenticated: true
    types:
      - admin
  - path: /users/
    at: /
    method: post
  - path: /users/login
    at: /login
    method: post
  - path: /users/:userId
    at: /:userId
    method: put
    authenticated: true
  - path: /users/:userId
    at: /:userId
    method: delete
    authenticated: true
  - path: /users/:userId/followed-groups
    at: /:userId/followed-groups
    method: put
    authenticated: true

# ms-groups
http://ms-groups$SERVICES_SUFFIX:
  - path: /ping/groups
    at: /ping
    method: get
  - path: /groups/:groupId
    at: /:groupId
    method: get
  - path: /groups
    at: /
    method: get
  - path: /groups
    at: /
    method: post
    authenticated: true
  - path: /groups/:groupId
    at: /:groupId
    method: put
    authenticated: true
  - path: /groups/:groupId
    at: /:groupId
    method: delete
    authenticated: true
  - path: /groups/followers/:userId
    at: /followers/:userId
    method: get

# ms-templates
http://ms-templates$SERVICES_SUFFIX:
  - path: /ping/templates
    at: /ping
    method: get
  - path: /templates/templates/:templateId
    at: /templates/:templateId
    method: get
  - path: /templates/templates
    at: /templates
    method: get
  - path: /templates/templates
    at: /templates
    method: post
    authenticated: true
  - path: /templates/templates/:templateId
    at: /templates/:templateId
    method: put
    authenticated: true
  - path: /templates/templates/:templateId
    at: /templates/:templateId
    method: delete
    authenticated: true

# ms-certificates
http://ms-certificate$SERVICES_SUFFIX:
  - path: /ping/certificates
    at: /ping
    method: get
  - path: /certificates
    method: post
    authenticated: true