version: "3.7"

services:
  vhost:
    image: jwilder/nginx-proxy:alpine
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./vhost.conf:/etc/nginx/conf.d/proxy_buffer_size.conf:ro

  zaqar:
    image: khaosdoctor/zaqar:v2.1.1
    environment:
      SENDGRID_APIKEY: $SENDGRID_APIKEY
      DEFAULT_FROM_ADDRESS: contato@chega.ai
      DEFAULT_FROM_NAME: Chega.aí
      RENDERER_LIST: zaqar-renderer-pug zaqar-renderer-mustache

  mongodb:
    image: mvertes/alpine-mongo:latest
    volumes:
      - ./mongodb/db:/data/db
      - ./mongodb/configdb:/data/configdb
    ports:
      - "27017:27017"

  ms-events:
    build: ./ms-events
    environment:
      VIRTUAL_HOST: ms-events.lvh.me
      DATABASE_MONGODB_URI: mongodb://mongodb:27017
      DATABASE_MONGODB_DBNAME: chegaai
      MICROSERVICES_USER_URL: http://ms-users:3000
      MICROSERVICES_GROUP_URL: http://ms-groups:3000
      AZURE_STORAGE_ACCOUNT_NAME: $AZURE_STORAGE_ACCOUNT_NAME
      AZURE_STORAGE_ACCOUNT_ACCESS_KEY: $AZURE_STORAGE_ACCOUNT_ACCESS_KEY
      AZURE_STORAGE_CONTAINER_NAME: events-dev
    command: ["npm", "run", "start:debug"]
    depends_on:
      - mongodb
      - ms-users
      - ms-groups
      - vhost

  ms-users:
    build: ./ms-users
    environment:
      VIRTUAL_HOST: ms-users.lvh.me
      DATABASE_MONGODB_URI: mongodb://mongodb:27017
      DATABASE_MONGODB_DBNAME: chegaai
      JWT_SECRET: $JWT_SECRET
      JWT_AUDIENCE: $JWT_AUDIENCE
    command: ["npm", "run", "start:debug"]
    depends_on:
      - mongodb
      - vhost

  ms-groups:
    build: ./ms-groups
    environment:
      VIRTUAL_HOST: ms-groups.lvh.me
      DATABASE_MONGODB_URI: mongodb://mongodb:27017
      DATABASE_MONGODB_DBNAME: chegaai
      MICROSERVICE_PROFILE_URL: http://ms-profiles:3000
      AZURE_STORAGE_ACCOUNT_NAME: $AZURE_STORAGE_ACCOUNT_NAME
      AZURE_STORAGE_ACCOUNT_ACCESS_KEY: $AZURE_STORAGE_ACCOUNT_ACCESS_KEY
      AZURE_STORAGE_CONTAINER_NAME: groups-dev
    command: ["npm", "run", "start:debug"]
    depends_on:
      - mongodb
      - ms-users
      - vhost

  ms-templates:
    build: ./ms-templates
    environment:
      VIRTUAL_HOST: ms-templates.lvh.me
      DATABASE_MONGODB_URI: mongodb://mongodb:27017
      DATABASE_MONGODB_DBNAME: chegaai
      MICROSERVICE_GROUP_URL: http://ms-groups:3000
      AZURE_STORAGE_ACCOUNT_NAME: $AZURE_STORAGE_ACCOUNT_NAME
      AZURE_STORAGE_ACCOUNT_ACCESS_KEY: $AZURE_STORAGE_ACCOUNT_ACCESS_KEY
      AZURE_STORAGE_CONTAINER_NAME: templates-dev
    command: ["npm", "run", "start:debug"]
    depends_on:
      - mongodb
      - ms-groups
      - vhost

  ms-certificate:
    build: ./ms-certificate
    environment:
      VIRTUAL_HOST: ms-certificate.lvh.me
      DATABASE_MONGODB_URI: mongodb://mongodb:27017
      DATABASE_MONGODB_DBNAME: chegaai
      MICROSERVICE_USER_URL: http://ms-users:3000
      MICROSERVICE_EVENT_URL: http://ms-events:3000
      MICROSERVICE_TEMPLATE_URL: http://ms-templates:3000
      AZURE_STORAGE_ACCOUNT_NAME: $AZURE_STORAGE_ACCOUNT_NAME
      AZURE_STORAGE_ACCOUNT_ACCESS_KEY: $AZURE_STORAGE_ACCOUNT_ACCESS_KEY
      AZURE_STORAGE_CONTAINER_NAME: certificates-dev
    depends_on:
      - vhost
      - mongodb
      - ms-users
      - ms-events
      - ms-templates

  api-gateway:
    build: ./api-gateway
    environment:
      VIRTUAL_HOST: api-gateway.192.168.15.31.nip.io
      MAPS_FILE_URL: $API_GATEWAY_CONFIG
      AUTH_JWT_AUDIENCE: $JWT_AUDIENCE
      AUTH_JWT_ISSUER: $JWT_ISSUER
      AUTH_JWT_SECRET: $JWT_SECRET
      AUTH_ALGORITHMS: HS256
    depends_on:
      - vhost
      - ms-events
      - ms-users
      - ms-groups
      - ms-templates
      - ms-certificate

  ms-profiles:
    build: ./ms-profiles
    environment:
      VIRTUAL_HOST: ms-profiles.lvh.me
      DATABASE_MONGODB_URI: mongodb://mongodb:27017
      DATABASE_MONGODB_DBNAME: chegaai
      CLIENTS_GROUP_URL: http://ms-groups:3000
      AZURE_STORAGE_ACCOUNT_NAME: $AZURE_STORAGE_ACCOUNT_NAME
      AZURE_STORAGE_ACCOUNT_ACCESS_KEY: $AZURE_STORAGE_ACCOUNT_ACCESS_KEY
      AZURE_STORAGE_CONTAINER_NAME: profile-dev
    depends_on:
      - vhost
      - mongodb

volumes:
  vhost.conf:
