version: "3.7"

services:
  vhost:
    image: jwilder/nginx-proxy:alpine
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  mongodb:
    image: mvertes/alpine-mongo:latest
    volumes:
      - ./mongodb/db:/data/db
      - ./mongodb/configdb:/data/configdb
    ports:
      - "27017:27017"

  ms-events:
      build: ./ms-events
      environment:
        VIRTUAL_HOST: ms-events.127.0.0.1.nip.io, ms-event.127.0.0.1.nip.io
        DATABASE_MONGODB_URI: mongodb://mongodb:27017
        DATABASE_MONGODB_DBNAME: chegaai
        MICROSERVICES_USER_URL: http://ms-users:3000
        MICROSERVICES_GROUP_URL: http://ms-groups:3000
      command: ["npm", "run", "start:debug"]
      depends_on:
        - mongodb
        - ms-users
        - ms-groups
        - vhost