version: "3.7"

services:
  vhost:
    image: jwilder/nginx-proxy:alpine
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  mongodb:
    image: mvertes/alpine-mongo:latest
    volumes:
      - ./mongodb/db:/data/db
      - ./mongodb/configdb:/data/configdb
    ports:
      - "27017:27017"

  ms-events:
    build: ./ms-events
    environment:
      VIRTUAL_HOST: ms-events.127.0.0.1.nip.io
      DATABASE_MONGODB_URI: mongodb://mongodb:27017
      DATABASE_MONGODB_DBNAME: chegaai
      MICROSERVICES_USER_URL: http://ms-users:3000
      MICROSERVICES_GROUP_URL: http://ms-groups:3000
    command: ["npm", "run", "start:debug"]
    depends_on:
      - mongodb
      - ms-users
      - ms-groups
      - vhost

  ms-users:
    build: ./ms-users
    environment:
      VIRTUAL_HOST: ms-users.127.0.0.1.nip.io
      DATABASE_MONGODB_URI: mongodb://mongodb:27017
      DATABASE_MONGODB_DBNAME: chegaai
      JWT_SECRET: mysupercomplicatedsecretshhhh
    command: ["npm", "run", "start:debug"]
    depends_on:
      - mongodb
      - vhost

  ms-groups:
    build: ./ms-groups
    environment:
      VIRTUAL_HOST: ms-groups.127.0.0.1.nip.io
      DATABASE_MONGODB_URI: mongodb://mongodb:27017
      DATABASE_MONGODB_DBNAME: chegaai
      MICROSERVICE_USER_URL: http://ms-users:3000
    command: ["npm", "run", "start:debug"]
    depends_on:
      - mongodb
      - ms-users
      - vhost

  ms-templates:
    build: ./ms-templates
    environment:
      VIRTUAL_HOST: ms-templates.127.0.0.1.nip.io
      DATABASE_MONGODB_URI: mongodb://mongodb:27017
      DATABASE_MONGODB_DBNAME: chegaai
      MICROSERVICE_GROUP_URL: http://ms-groups:3000
      AZURE_STORAGE_ACCOUNT_NAME: $MS_TEMPLATES_AZURE_STORAGE_ACCOUNT_NAME
      AZURE_STORAGE_ACCOUNT_ACCESS_KEY: $MS_TEMPLATES_AZURE_STORAGE_ACCOUNT_ACCESS_KEY
      AZURE_STORAGE_ACCOUNT_ACCESS_KEY: $MS_TEMPLATES_AZURE_STORAGE_ACCOUNT_ACCESS_KEY
    command: ["npm", "run", "start:debug"]
    depends_on:
      - mongodb
      - ms-groups
      - vhost

  ms-certificate:
    build: ./ms-certificate
    environment:
      VIRTUAL_HOST: ms-certificate.127.0.0.1.nip.io
      DATABASE_MONGODB_URI: mongodb://mongodb:27017
      DATABASE_MONGODB_DBNAME: chegaai
      MICROSERVICE_USER_URL: http://ms-users:3000
      MICROSERVICE_EVENT_URL: http://ms-events:3000
      MICROSERVICE_TEMPLATE_URL: http://ms-templates:3000
      AZURE_STORAGE_ACCOUNT_NAME: $MS_CERTIFICATE_AZURE_STORAGE_ACCOUNT_NAME
      AZURE_STORAGE_ACCOUNT_ACCESS_KEY: $MS_CERTIFICATE_AZURE_STORAGE_ACCOUNT_ACCESS_KEY
      AZURE_STORAGE_CONTAINER_NAME: $MS_CERTIFICATE_AZURE_STORAGE_CONTAINER_NAME
    depends_on:
      - vhost
      - mongodb
      - ms-users
      - ms-events
      - ms-templates